version: '3.5'

services:
  postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./main/resources/sql/01-createTables.sql:/docker-entrypoint-initdb.d/01-createTables.sql
      - ./main/resources/sql/02-fillTables.sql:/docker-entrypoint-initdb.d/02-fillTables.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
  pg_data:
    external: false
